"""initial migrate

Revision ID: 5cc62ca5b7e6
Revises: 7a49da786d80
Create Date: 2025-08-17 23:36:15.723724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc62ca5b7e6'
down_revision: Union[str, Sequence[str], None] = '7a49da786d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('balance detalization',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.Column('old_balance', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('operation', sa.Enum('DEPOSIT', 'WITHDRAW', name='operations'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('new_balance', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('balance detalization')
    op.drop_table('wallets')
    # ### end Alembic commands ###
